name: Student Registration Form CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build
        run: |
          echo "Building Student Registration Project..."
          test -f index.html
          echo "HTML file found successfully."

      - name: Run HTML Tests
        run: |
          python test.py